### ISSUE TITLE
 0.10.0: error loading MC classes on Fabric, TypeNotPresentException on Forge

### ISSUE THREAD

**Issue by natanfudge** [shedaniel/architect-plugin#23]
- `git clone --branch forge https://github.com/natanfudge/not-enough-crashes`
- `gradlew fabric:runClient`: works
- IntelliJ `Minecraft Client [:fabric]`: 
![image](https://user-images.githubusercontent.com/25990014/134957408-129cfdfb-af9b-44a8-bbcf-3037f2d32d97.png)
- `gradlew forge:runClient` / IntelliJ: 
![image](https://user-images.githubusercontent.com/25990014/134957644-a7f516ee-9fb2-4076-a19c-ec9b9b70420c.png)

**Comment by shedaniel** [comment]
Should be fixed in 954fbc55a63bf978bb67d18f606c048fe57832d1
