### ISSUE TITLE
Unable to disable Legacy Mixin AP with Architectury plugin enabled

### ISSUE THREAD

**Issue by JT122406** [shedaniel/architect-plugin#41]
In loom 1.5 disabling Legacy AP became much larger, however arch plugin doesn't support this as it looks for refmap

**Comment by JT122406** [comment]
This is seemly fixed in the last 2 commits however from my testing it still adds the refmap json for the mixins in common to the jar.  This should not be the case as there should be no refmaps in the fabric jar at all if this option is disabled

**Comment by shedaniel** [comment]
Are you sure you are on the latest version and not just gradle caching the first version? It shouldn't add the refmap name in my testing.

**Comment by JT122406** [comment]
> Are you sure you are on the latest version and not just gradle caching the first version? It shouldn't add the refmap name in my testing.

Based on my testing this is with legacy ap disabled just in the fabric project
![image](https://github.com/architectury/architectury-plugin/assets/75751882/86748651-0906-487b-aec6-3c3a32e41eda)
This is with it disabled in fabric and common:
![image](https://github.com/architectury/architectury-plugin/assets/75751882/d2236259-3dd3-4b4d-a6df-8baefe3aedc9)
However with this option the forge jar is missing the refmap:
![image](https://github.com/architectury/architectury-plugin/assets/75751882/a59598e7-544c-4727-be54-b09d88ff6405)
